sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
script:
- pycodestyle uw_hfs
- coverage run uw_hfs/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_hfs/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_hfs/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: nxLqPC41SVu3y3FRO4lDJJoMbp/SbteeiDjYS+XUn4O4Q1pU+iqVxeriHVkqMLJmutK9QQAi5JGgRqVZrWg/XuW5skLk58AaaJQol+6IU0b4wjxJAT/ybxtC7QgV51OPWdsBefCVEI9q3l42G2VqZhOFC0qr3S3QzogF6dyHj63lD7ASw9CGSVnnoF/1zZLlGLoo4jmsStOWqzPxdDzSlHdnG1ZnYIanOLMHsjfcl3ErdCizBZ1Q1FS4mIkQDkD1pJzcegq4LD1iKJmZ7d3ydFvbrDanifRz1oPCj5a0SMRqL947MosdfLYK4SAGs7EKXGuoKsgMTUT6RPvFt1FlW1mNyAiYqEf+rdaFyohCfrD1Pu+uuUaQnNaOJPZm2/Ue2I0LvBSG4xlfjqhmUmxgEN+KAmkqgv42/2nPaPMcWUs8D0lrdZtPUWRKyV2PWVJLVB0W78YhkDeg1441ua8uiCbdpynDKDfir7sMRaZHESqVcrkbaLQQ2vT76Qr0QrnsjAUq2ldlW44GDS/h8g/6QD5S+3ec518pdd2K1WSmQnh5gSB+BBwHoNdZ9zuAUiHj84m0Sm06O9imxTyfxbyzKElICsjoReKpDGgg5arz920kLFbSjUDvhtYR65huLTGS7Oad47XM+O7ah2g3bvdBG24RnApAN3SPKhopVnwxXYk=
  on:
    tags: true
    python: '3.5'
